spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/db_pokemon?useSSL=false&serverTimezone=America/Mexico_City
    username: user_pokemon
    password: poke
server:  
  port: 8080