//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.28 at 02:13:31 PM CDT 
//


package pokemon.api.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pokemon.api.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pokemon.api.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AbilitiesRequest }
     * 
     */
    public AbilitiesRequest createAbilitiesRequest() {
        return new AbilitiesRequest();
    }

    /**
     * Create an instance of {@link AbilitiesResponse }
     * 
     */
    public AbilitiesResponse createAbilitiesResponse() {
        return new AbilitiesResponse();
    }

    /**
     * Create an instance of {@link Ability }
     * 
     */
    public Ability createAbility() {
        return new Ability();
    }

    /**
     * Create an instance of {@link IdRequest }
     * 
     */
    public IdRequest createIdRequest() {
        return new IdRequest();
    }

    /**
     * Create an instance of {@link IdResponse }
     * 
     */
    public IdResponse createIdResponse() {
        return new IdResponse();
    }

    /**
     * Create an instance of {@link NameRequest }
     * 
     */
    public NameRequest createNameRequest() {
        return new NameRequest();
    }

    /**
     * Create an instance of {@link NameResponse }
     * 
     */
    public NameResponse createNameResponse() {
        return new NameResponse();
    }

    /**
     * Create an instance of {@link GetCountryRequest }
     * 
     */
    public GetCountryRequest createGetCountryRequest() {
        return new GetCountryRequest();
    }

    /**
     * Create an instance of {@link GetCountryResponse }
     * 
     */
    public GetCountryResponse createGetCountryResponse() {
        return new GetCountryResponse();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

}
